FROM python:3.7-slim-buster

MAINTAINER Balla "insim@insim.to"

WORKDIR /app
COPY ballachatbot.py /app

RUN apt update && apt install -y python3-pip
COPY . ./
RUN pip3 install nltk --no-cache-dir

ENTRYPOINT [ "python3.7", "./ballachat.py" ]


